version: '3.3'

services:

  app:
    build: ./src
    command: python app.py
    ports:
      - "5000:5000"
    networks:
      - network-app
    volumes:
      - ./src:/app
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    hostname: sprc_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO-INITDB-DATABASE: temp_db
    ports:
      - "27017:27017"
    volumes:
      - ./db/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks:
      - network-app
      - network-express

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    links:
      - mongo
    networks:
      - network-express

networks:
  network-app: {}
  network-express: {}
